name: Playwright workflow

on: 
  workflow_dispatch:

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    steps:
       # Checkout the current repository
      - name: Checkout this repository
        uses: actions/checkout@v4

        # Checkout another repository (e.g. org/other-repo)
      - name: Checkout to playwright-basic-project repository
        uses: actions/checkout@v4
        with:
          repository: aviranaviv/playwright-basic-project  # Replace with the owner/repo of the target
          ref: main # Optional: specify branch, tag or SHA
          path: playwright-basic-project # Optional: folder name for the checked-out repo

      - name: Install node latest version
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
        working-directory: playwright-basic-project

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium
        working-directory: playwright-basic-project

      - name: Run Playwright Tests with Allure results
        run: |
          npx playwright test --reporter=html,allure-playwright
        working-directory: playwright-basic-project

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Upload Playwright HTML Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-with-cicd/playwright-report/
          retention-days: 30

      
